_wandb:
    value:
        cli_version: 0.19.4
        code_path: code/test_script.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.8.20
            "5": 0.19.4
            "8":
                - 3
                - 8
            "12": 0.19.4
            "13": windows-amd64
CR:
    value: 0.1
activation:
    value: relu
dense_units:
    value: 512
entropy:
    value: 0.01
env_name:
    value: myoTorsoFixed-v0
loaded_model:
    value: N/A
lr:
    value: 0.0002
max_episode_steps:
    value: 200
name:
    value: "2025_03_19_19_40_037"
num_envs:
    value: 8
policy_type:
    value: PPO
seed:
    value: 7
total_timesteps:
    value: 20000000
